services:
  - type: web
    name: guapiecotour
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ORS_API_KEY
        sync: false
    plan: free